"""add activities claims claim_files badges tables

Revision ID: 2c8b3d174a11
Revises: 6ec5abb724e4
Create Date: 2026-03-23 13:10:51.795791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c8b3d174a11'
down_revision: Union[str, Sequence[str], None] = '6ec5abb724e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('required_proof_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('badge_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_title'), 'activities', ['title'], unique=True)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_category', sa.String(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('required_activities', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('is_individual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_badge_category'), 'badges', ['badge_category'], unique=False)
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AI_PROCESSING', 'APPROVED', 'REJECTED', 'MANUAL_REVIEW', name='claimstatus'), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'section')
    op.drop_table('claim_files')
    op.drop_table('claims')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_badge_category'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_activities_title'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
