"""add_current_year_to_user

Revision ID: bafed1eb9cdf
Revises: 2c8b3d174a11
Create Date: 2026-03-24 13:39:48.665220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafed1eb9cdf'
down_revision: Union[str, Sequence[str], None] = '2c8b3d174a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_year')
    # ### end Alembic commands ###
