"""Init full models

Revision ID: cecac045ac26
Revises: bafed1eb9cdf
Create Date: 2026-03-28 19:05:35.490788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cecac045ac26'
down_revision: Union[str, Sequence[str], None] = 'bafed1eb9cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_deductions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('total_points_deducted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_deductions_batch_id'), 'batch_deductions', ['batch_id'], unique=True)
    op.add_column('claims', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('reviewer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'claims', 'users', ['reviewer_id'], ['id'])
    op.add_column('users', sa.Column('assigned_faculty_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['assigned_faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_faculty_id')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'reviewer_id')
    op.drop_column('claims', 'notes')
    op.drop_index(op.f('ix_batch_deductions_batch_id'), table_name='batch_deductions')
    op.drop_table('batch_deductions')
    # ### end Alembic commands ###
